Repository Ionfinisher/30-days-of-open-source, pull requests merged in 2025-10, with the labels that each got.

#29 Revert "Revert "feat: Implement basic Question class with verifierResponse method. Closes #2""
  src/java/quiz/src/Question.java
Labels: hacktoberfest

#27 feat: Add MULTIPLE_CHOICE support to Question class
  src/java/quiz/src/Question.java
  src/java/quiz/src/QuestionType.java
Labels: 🔥 200

#34 Ajout du prototype **Dashboard des participants** pour le projet *30 Days of Open Source*.
  designs/maquette.md
Labels: 🔥 1500
